name: Android build normal

on:
  workflow_dispatch:

jobs:
  linter:
      name: Linter
      runs-on: ubuntu-latest
      timeout-minutes: 10
      steps: 
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            channel: beta
            cache: true
        - run: flutter pub get
        - run: flutter analyze --no-fatal-infos --no-fatal-warnings 
  formater:
    name: Formating
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: beta
          cache: true
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: "beta"
        cache: true
    - run: flutter pub get
    - run: flutter build apk --flavor full --target lib/main_without_firebase.dart
    - run: flutter build apk --split-per-abi --flavor full --target lib/main_without_firebase.dart

    - uses: actions/upload-artifact@v3
      with:
        name: arm-v8a
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
