name: Android build normal

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: "beta"
        cache: true
    - run: flutter pub get
    - run: flutter build apk --flavor full --target lib/main.dart
    - run: flutter build apk --split-per-abi --flavor full --target lib/main.dart

    - uses: actions/upload-artifact@v3
      with:
        name: arm-v8a
        path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk