name: Gh-Pages deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - uses: subosito/flutter-action@v1
      - run: flutter build web -t  lib/main_without_firebase.dart --web-renderer canvaskit --base-href "/todo_list/"
      - uses: bluefireteam/flutter-gh-pages@v7
        